stages:
  - deploy

Deploy to Heroku:
  stage: deploy
  image: ruby:latest
  only:
    - main
  script:
    - gem install dpl
    - dpl --provider=heroku --app=latihanchapter8 --api-key=d69f2be5-382d-4469-82af-f657570db327
